dist: trusty

language:
  - go

go:
  - 1.10.x

git:
depth: 1

notifications:
  email: false

install:
  - go get -u golang.org/x/lint/golint
  - wget https://sonarsource.bintray.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.2.0.1227-linux.zip
  - unzip sonar-scanner-cli-3.2.0.1227-linux.zip -d /opt
  - export PATH=$PATH:/opt/sonar-scanner-3.2.0.1227-linux/bin

script:
  - golint -set_exit_status
  - make test
  - sonar-scanner
    -Dsonar.login=$SONAR_TOKEN
    -Dsonar.host.url=https://sonarcloud.io
    -Dsonar.organization=sewandevs
